# Generated by Django 4.2.5 on 2023-10-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rccwe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='images',
        ),
    ]
