# Generated by Django 4.2.6 on 2023-11-02 22:31

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('rccwe', '0006_delete_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmation_token', models.CharField(default=secrets.token_urlsafe, max_length=64)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
