# Generated by Django 4.2.6 on 2023-11-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rccwe', '0007_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
